<?php

class msOrderPropertiesCreateProcessor extends modObjectCreateProcessor {
	public $classKey = 'msOrderProperties';
	public $languageTopics = array('minishop2');
	public $permission = 'msorder_save';


	/** {@inheritDoc} */
	public function initialize() {
		if (!$this->modx->hasPermission($this->permission)) {
			return $this->modx->lexicon('access_denied');
		}
		return parent::initialize();
	}

    public function afterSave()
    {

        $this->object->generateLexiconEntry();

        return parent::afterSave(); // TODO: Change the autogenerated stub
    }


}

return 'msOrderPropertiesCreateProcessor';